### Gateway - Info actuator
GET {{gateway}}/actuator/health

### Gateway - Register User
POST {{gateway}}/auth/register-user
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "username": "user",
  "password": "pass",
  "roles": ["read", "write"]
}

### Gateway - Generate JWT token
POST {{gateway}}/auth/token
Content-Type: application/json
Authorization: Basic dnunez pass

{
  "username": "dnunez",
  "password": "pass"
}
> {% client.global.set("auth_token", response.body.token) %}


### Register User
POST {{auth-service}}/auth/register-user
Content-Type: application/json

{
  "username": "user",
  "password": "pass",
  "roles": ["read", "write"]
}

### Generate JWT token
POST {{auth-service}}/auth/token
Content-Type: application/json
Authorization: Basic dnunez pass

{
  "username": "dnunez",
  "password": "pass"
}
> {% client.global.set("auth_token", response.body.token) %}


### Access home endpoint
GET {{auth-service}}
Authorization: Bearer {{auth_token}}


### Access secured endpoint read authority
GET {{auth-service}}/secured-read
Authorization: Bearer {{auth_token}}

### Access secured endpoint write authority
GET {{auth-service}}/secured-write
Authorization: Bearer {{auth_token}}

