{
 "title": "Logs, Traces, Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "traceID", "label": "Trace ID", "query": "label_values(traceID)" }
  ]
 },
 "panels": [
  {
   "title": "Logs with trace ID $traceID",
   "type": "logs",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{traceID=\"$traceID\"}"
    }
   ]
  },
  {
   "title": "Trace View for trace with id $traceID",
   "type": "traces",
   "gridPos": { "h": 15, "w": 23, "x": 0, "y": 10 },
   "targets": [
    { "limit": 20, "tableType": "traces", "query": "$traceID" }
   ]
  },
  {
   "title": "latency for All",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(1.00, sum(rate(http_server_requests_seconds_bucket{uri=~\".*\"}[$__rate_interval])) by (le))",
     "legendFormat": "max"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{uri=~\".*\"}[$__rate_interval])) by (le))",
     "legendFormat": "tp99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{uri=~\".*\"}[$__rate_interval])) by (le))",
     "legendFormat": "tp95"
    }
   ]
  }
 ]
}