server:
  port: 9090

# For service discovery
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: auth-service
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: config-service

# Use service discovery (spring.cloud.config.discovery.enabled=true) instead of the manual config server url
  config:
    import: 'configserver:'
