server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file://${user.home}/config-repo
          clone-on-start: true
      fail-fast: true
  config:
    import: "configserver:http://localhost:${server.port}/?fail-fast=true&max-attempts=10&max-interval=1500&multiplier=1.2&initial-interval=1100"

