server:
  port: 8888

# Register config server to the service discovery server so other services find this one
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file:///${user.home}/wa/spring-config-server-data-repo
          #uri: https://github.com/silver-mx/spring-config-server-data-repo
          clone-on-start: true
