server:
  port: 9297

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: http://config.url
          clone-on-start: true

  config:
    import: configserver:http://localhost:${server.port}