### Spring Data REST - Fetch all bugs
GET http://localhost:8080/bugs?page=1&size=5

### Spring Data REST - Fetch a specific bug
GET http://localhost:8080/bugs/1234

### Fetch a specific bug
GET http://localhost:8080/test/bugs/1234

### Fetch all bugs - Throws MultipleBagFetchException
GET http://localhost:8080/test/bugs

### Fetch all bugs - Optimized JPA query
GET http://localhost:8080/test/bugs-optimized-jpa

### Fetch all bugs Dto
GET http://localhost:8080/test/bugs-optimized-jpa-dto

### Fetch all bugs - Optimized Blazed-Persistence query
GET http://localhost:8080/test/bugs-optimized-blazed

### Fetch all bugs - Entity Graph
GET http://localhost:8080/test/bugs-entity-graph

### Add tag to bug with pessimistic locking and increase version
PATCH http://localhost:8080/test/add-tag-pessimistic-lock/1234/pessimitic-new-tag

### Add tag to bug with optimistic locking
PATCH http://localhost:8080/test/add-tag-optimistic-lock/1234/optimistic-new-tag
